<?php
/**
 * Tax Cabinet — Language File
 * Поддерживаемые языки: ru (русский), kz (қазақша), en (English)
 */

if (!isset($_SESSION)) session_start();

// Определить текущий язык
function getCurrentLang(): string {
    if (!empty($_SESSION['lang']) && in_array($_SESSION['lang'], ['ru','kz','en'])) {
        return $_SESSION['lang'];
    }
    return 'ru';
}

// Установить язык
function setLangSession(string $code): void {
    if (in_array($code, ['ru','kz','en'])) {
        $_SESSION['lang'] = $code;
    }
}

// Получить перевод
function t(string $key, array $vars = []): string {
    global $LANG;
    $lang = getCurrentLang();
    $text = $LANG[$lang][$key] ?? $LANG['ru'][$key] ?? $key;
    foreach ($vars as $k => $v) {
        $text = str_replace('{' . $k . '}', $v, $text);
    }
    return $text;
}

// Обработка AJAX смены языка
if (!empty($_POST['set_lang'])) {
    setLangSession($_POST['set_lang']);
    header('Content-Type: application/json');
    echo json_encode(['ok' => true, 'lang' => $_SESSION['lang']]);
    exit;
}

// ============================================================
//  СЛОВАРИ
// ============================================================
$LANG = [

// ============================================================
// РУССКИЙ
// ============================================================
'ru' => [

  // --- Общие ---
  'site_name'            => 'Кабинет налогоплательщика',
  'site_sub'             => 'Республика Казахстан',
  'loading'              => 'Загрузка...',
  'save'                 => 'Сохранить',
  'cancel'               => 'Отмена',
  'close'                => 'Закрыть',
  'delete'               => 'Удалить',
  'edit'                 => 'Редактировать',
  'back'                 => 'Назад',
  'back_to_list'         => 'Назад к списку',
  'continue'             => 'Продолжить',
  'submit'               => 'Подать',
  'confirm'              => 'Подтвердить',
  'yes'                  => 'Да',
  'no'                   => 'Нет',
  'search'               => 'Поиск',
  'filter'               => 'Фильтр',
  'all'                  => 'Все',
  'none'                 => 'Нет',
  'required_field'       => 'Обязательное поле',
  'optional_field'       => 'Необязательно',
  'error'                => 'Ошибка',
  'success'              => 'Успешно',
  'warning'              => 'Предупреждение',
  'info'                 => 'Информация',
  'not_found'            => 'Не найдено',
  'access_denied'        => 'Доступ запрещён',
  'unknown_error'        => 'Неизвестная ошибка',
  'copied'               => 'Скопировано',
  'show_all'             => 'Показать все',
  'go_to_doc'            => 'Перейти к документу',
  'open'                 => 'Открыть',
  'download'             => 'Скачать',
  'print'                => 'Печать',
  'view'                 => 'Просмотр',
  'sign'                 => 'Подписать',
  'send'                 => 'Отправить',
  'year'                 => 'Год',
  'period'               => 'Период',
  'date'                 => 'Дата',
  'sum'                  => 'Сумма',
  'action'               => 'Действие',
  'type'                 => 'Тип',
  'status'               => 'Статус',
  'name'                 => 'Наименование',
  'inn'                  => 'ИИН',
  'bin'                  => 'БИН',
  'inn_bin'              => 'ИИН/БИН',
  'phone'                => 'Телефон',
  'email'                => 'Email',
  'address'              => 'Адрес',
  'created_at'           => 'Дата создания',
  'updated_at'           => 'Дата обновления',
  'language'             => 'Язык',
  'settings'             => 'Настройки',
  'help'                 => 'Помощь',
  'logout'               => 'Выйти',
  'my_profile'           => 'Мой профиль',
  'hotline'              => 'Горячая линия',
  'telegram_bot'         => 'Телеграм-бот',
  'copyright'            => '© {year} Министерство финансов РК',
  'privacy'              => 'Политика конфиденциальности',
  'terms'                => 'Условия использования',

  // --- Навигация ---
  'nav_services'         => 'Услуги',
  'nav_account'          => 'Лицевой счёт',
  'nav_services_menu'    => 'Сервисы',
  'nav_documents'        => 'Документы',
  'nav_submit_doc'       => 'Подать декларацию',
  'nav_representatives'  => 'Представители',
  'nav_profile'          => 'Профиль',
  'nav_overview'         => 'Обзор',
  'nav_history'          => 'История платежей',
  'nav_debts'            => 'Задолженности',
  'nav_overpayment'      => 'Переплата',
  'nav_charges'          => 'Начисления',
  'nav_calculator'       => 'Калькулятор налогов',
  'nav_notifications'    => 'Уведомления',
  'nav_messages'         => 'Сообщения',
  'nav_all_documents'    => 'Все документы',
  'nav_incoming'         => 'Входящие',
  'nav_new_document'     => 'Новый документ',
  'nav_feedback'         => 'Обратная связь',
  'nav_submit_btn'       => 'Подать декларацию',
  'nav_support'          => 'Поддержка',
  'nav_help'             => 'Справочный центр',

  // --- Статусы ---
  'status_draft'         => 'Черновик',
  'status_submitted'     => 'На рассмотрении',
  'status_in_review'     => 'Проверяется',
  'status_accepted'      => 'Принято',
  'status_rejected'      => 'Отклонено',
  'status_cancelled'     => 'Отменено',
  'status_paid'          => 'Оплачено',
  'status_unpaid'        => 'Не оплачено',
  'status_overdue'       => 'Просрочено',
  'status_new'           => 'Новое',
  'status_read'          => 'Прочитано',

  // --- Дашборд ---
  'dashboard_title'      => 'Личный кабинет',
  'dashboard_welcome'    => 'Добро пожаловать',
  'my_documents'         => 'Мои документы',
  'incoming_documents'   => 'Входящие документы',
  'messages'             => 'Сообщения',
  'submit_documents'     => 'Подать документы',
  'representatives_card' => 'Представители',
  'no_documents'         => 'Документов пока нет',
  'no_incoming'          => 'Входящих документов нет',
  'no_messages'          => 'Сообщений пока нет',
  'no_representatives'   => 'Представители не добавлены',
  'no_notifications'     => 'Уведомлений нет',
  'tab_my_docs'          => 'Мои документы',
  'tab_incoming'         => 'Входящие',
  'doc_form'             => 'Форма',
  'doc_date'             => 'Дата',
  'doc_status'           => 'Статус',
  'doc_actions'          => 'Действия',
  'user_type_individual' => 'Физическое лицо',
  'user_type_ip'         => 'Индивидуальный предприниматель',
  'user_type_legal'      => 'Юридическое лицо',

  // --- Лицевой счёт (account.php) ---
  'account_title'        => 'Лицевой счёт',
  'account_overview'     => 'Обзор',
  'account_documents'    => 'Документы',
  'account_history'      => 'История платежей',
  'account_debts'        => 'Задолженности',
  'account_overpayment'  => 'Переплата',
  'account_charges'      => 'Начисления',
  'account_profile'      => 'Профиль',
  'total_documents'      => 'Всего документов',
  'total_debt'           => 'Сумма задолженности',
  'total_overpayment'    => 'Сумма переплаты',
  'paid_current_year'    => 'Оплачено в этом году',
  'recent_documents'     => 'Последние документы',
  'recent_activity'      => 'Последние действия',
  'payment_history'      => 'История платежей',
  'debts_label'          => 'Задолженности',
  'overpayment_label'    => 'Переплата',
  'charges_label'        => 'Начисления',
  'no_debts'             => 'Задолженностей нет',
  'no_overpayment'       => 'Переплат нет',
  'no_charges'           => 'Начислений нет',
  'no_history'           => 'История платежей пуста',
  'debt_progress'        => 'Прогресс погашения',
  'paid_amount'          => 'Оплачено',
  'remaining_amount'     => 'Остаток',
  'charge_type'          => 'Вид начисления',
  'charge_period'        => 'Период',
  'charge_amount'        => 'Сумма начисления',
  'charge_paid'          => 'Оплачено',
  'charge_balance'       => 'Баланс',
  'filter_all'           => 'Все',
  'filter_year'          => 'Год',
  'doc_filter_status'    => 'Статус',
  'delete_draft'         => 'Удалить черновик',

  // --- Документы ---
  'documents_title'      => 'Документы',
  'doc_number'           => '№ документа',
  'doc_type'             => 'Тип декларации',
  'doc_period'           => 'Налоговый период',
  'doc_submitted_at'     => 'Дата подачи',
  'doc_created_at'       => 'Дата создания',
  'doc_view'             => 'Просмотр',
  'doc_continue'         => 'Продолжить',
  'doc_delete'           => 'Удалить',
  'doc_download_pdf'     => 'Скачать PDF',
  'doc_view_pdf'         => 'Просмотр PDF',
  'doc_sign'             => 'Подписать ЭЦП',
  'doc_submit'           => 'Подать декларацию',
  'no_docs_found'        => 'Документов не найдено',
  'search_docs'          => 'Поиск по документам',
  'advanced_filter'      => 'Фильтры',

  // --- Просмотр документа ---
  'doc_view_title'       => 'Просмотр документа',
  'doc_info'             => 'Информация о документе',
  'taxpayer'             => 'Налогоплательщик',
  'doc_timeline'         => 'История обработки',
  'timeline_created'     => 'Создан',
  'timeline_submitted'   => 'Подан на рассмотрение',
  'timeline_review'      => 'На проверке',
  'timeline_final'       => 'Итоговый статус',
  'timeline_pending'     => 'Ожидает',
  'doc_comment'          => 'Комментарий',
  'doc_reject_reason'    => 'Причина отклонения',
  'doc_form_data'        => 'Данные декларации',
  'doc_no_data'          => 'Данные не заполнены',
  'support_info'         => 'Нужна помощь?',
  'support_text'         => 'Свяжитесь с нами через Telegram или горячую линию.',
  'status_sub_draft'     => 'Черновик не подан',
  'status_sub_submitted' => 'Ожидает рассмотрения',
  'status_sub_inreview'  => 'Идёт проверка',
  'status_sub_accepted'  => 'Декларация принята',
  'status_sub_rejected'  => 'Декларация отклонена',
  'status_sub_cancelled' => 'Документ отменён',

  // --- Уведомления ---
  'notifications_title'  => 'Уведомления',
  'notif_all'            => 'Все уведомления',
  'notif_unread'         => 'Непрочитанные',
  'notif_read'           => 'Прочитанные',
  'notif_mark_all'       => 'Отметить все прочитанными',
  'notif_del_read'       => 'Удалить прочитанные',
  'notif_types_title'    => 'По типу',
  'notif_clear_filter'   => 'Сбросить фильтр',
  'notif_empty_all'      => 'Нет уведомлений',
  'notif_empty_unread'   => 'Все уведомления прочитаны',
  'notif_empty_sub'      => 'Здесь будут отображаться уведомления о ваших документах и налогах',
  'notif_empty_sub_read' => 'Нет прочитанных уведомлений',
  'notif_mark_read'      => 'Отметить прочитанным',
  'notif_count'          => 'уведомлений',
  'notif_unread_count'   => 'непрочитанных',
  'confirm_del_read'     => 'Удалить все прочитанные уведомления?',
  'notif_toast_marked'   => 'Все уведомления прочитаны',
  'notif_toast_deleted'  => 'Прочитанные уведомления удалены',
  'notif_type_document'  => 'Документы',
  'notif_type_deadline'  => 'Сроки',
  'notif_type_system'    => 'Система',
  'notif_type_payment'   => 'Платежи',
  'notif_min_ago'        => '{n} мин. назад',
  'notif_hour_ago'       => '{n} ч. назад',
  'notif_day_ago'        => '{n} д. назад',
  'notif_week_ago'       => '{n} нед. назад',
  'notif_just_now'       => 'Только что',
  'notif_read_at'        => 'Прочитано',
  'notif_pagination'     => 'Страница {page} из {total}',

  // --- Профиль ---
  'profile_title'        => 'Профиль',
  'profile_personal'     => 'Личные данные',
  'profile_contacts'     => 'Контактная информация',
  'profile_security'     => 'Безопасность',
  'profile_settings'     => 'Настройки',
  'profile_ecp'          => 'ЭЦП',
  'profile_fullname'     => 'ФИО',
  'profile_lastname'     => 'Фамилия',
  'profile_firstname'    => 'Имя',
  'profile_midname'      => 'Отчество',
  'profile_birthdate'    => 'Дата рождения',
  'profile_user_type'    => 'Тип налогоплательщика',
  'profile_reg_date'     => 'Дата регистрации',
  'profile_last_login'   => 'Последний вход',
  'change_password'      => 'Сменить пароль',
  'current_password'     => 'Текущий пароль',
  'new_password'         => 'Новый пароль',
  'confirm_password'     => 'Подтвердите пароль',
  'password_changed'     => 'Пароль успешно изменён',
  'password_error'       => 'Неверный текущий пароль',
  'passwords_not_match'  => 'Пароли не совпадают',
  'password_too_short'   => 'Пароль должен быть не менее 6 символов',
  'profile_saved'        => 'Данные сохранены',

  // --- Вход / Регистрация ---
  'login_title'          => 'Вход в кабинет',
  'login_iin'            => 'ИИН',
  'login_password'       => 'Пароль',
  'login_submit'         => 'Войти',
  'login_ecp'            => 'Войти через ЭЦП',
  'login_no_account'     => 'Нет аккаунта?',
  'login_register'       => 'Зарегистрироваться',
  'login_forgot'         => 'Забыли пароль?',
  'login_error'          => 'Неверный ИИН или пароль',
  'login_blocked'        => 'Аккаунт заблокирован',
  'register_title'       => 'Регистрация',
  'register_step1'       => 'Личные данные',
  'register_step2'       => 'Безопасность',
  'register_step3'       => 'ЭЦП',
  'register_iin'         => 'ИИН (12 цифр)',
  'register_lastname'    => 'Фамилия',
  'register_firstname'   => 'Имя',
  'register_midname'     => 'Отчество',
  'register_birthdate'   => 'Дата рождения',
  'register_phone'       => 'Телефон',
  'register_email'       => 'Email',
  'register_password'    => 'Пароль (минимум 6 символов)',
  'register_password2'   => 'Повторите пароль',
  'register_submit'      => 'Зарегистрироваться',
  'register_have_account'=> 'Уже есть аккаунт?',
  'register_login'       => 'Войти',
  'register_iin_invalid' => 'ИИН должен содержать 12 цифр',
  'register_iin_exists'  => 'Пользователь с таким ИИН уже зарегистрирован',
  'register_ecp_info'    => 'После регистрации будет автоматически сгенерирован сертификат ЭЦП (.p12)',
  'register_success_title'=> 'Регистрация завершена!',
  'register_personal_data'=> 'Персональные данные',
  'register_password_data'=> 'Пароль и безопасность',
  'password_strength_1'  => 'Слабый',
  'password_strength_2'  => 'Нормальный',
  'password_strength_3'  => 'Хороший',
  'password_strength_4'  => 'Сильный',
  'passwords_match'      => 'Пароли совпадают',

  // --- Калькулятор ---
  'calculator_title'     => 'Калькулятор налогов',
  'calc_tax_type'        => 'Вид налога',
  'calc_income'          => 'Доход',
  'calc_deduction'       => 'Вычеты',
  'calc_result'          => 'Результат расчёта',
  'calc_tax_amount'      => 'Сумма налога',
  'calc_calculate'       => 'Рассчитать',
  'calc_reset'           => 'Сбросить',
  'calc_opv'             => 'ОПВ (пенсионные)',
  'calc_co'              => 'СО (соц. отчисления)',
  'calc_osms'            => 'ОСМС',
  'calc_ipn'             => 'ИПН (индивидуальный подоходный)',
  'calc_sn'              => 'СН (социальный налог)',

  // --- Формы деклараций ---
  'form_title'           => 'Форма {code}',
  'form_taxpayer_info'   => 'Сведения о налогоплательщике',
  'form_tax_period'      => 'Налоговый период',
  'form_correction'      => 'Корректировка',
  'form_correction_num'  => 'Номер корректировки',
  'form_is_correction'   => 'Является корректировочной',
  'form_sign_date'       => 'Дата подписания',
  'form_next'            => 'Далее',
  'form_prev'            => 'Назад',
  'form_save_draft'      => 'Сохранить черновик',
  'form_submit'          => 'Подписать и подать',
  'form_ecp_required'    => 'Для подписи требуется ЭЦП',
  'form_saved'           => 'Черновик сохранён',
  'form_submitted'       => 'Декларация подана успешно',

  // --- Поля деклараций ---
  'field_iin'            => 'ИИН',
  'field_bin'            => 'БИН',
  'field_fullname'       => 'ФИО / Наименование',
  'field_phone'          => 'Телефон',
  'field_email'          => 'Email',
  'field_address'        => 'Адрес',
  'field_tax_office'     => 'Налоговый орган',
  'field_year'           => 'Год',
  'field_period'         => 'Период',
  'field_revenue'        => 'Совокупный доход',
  'field_income'         => 'Доход',
  'field_total_income'   => 'Итого доходы',
  'field_total_deduct'   => 'Итого вычеты',
  'field_tax_base'       => 'Налоговая база',
  'field_tax_rate'       => 'Ставка налога',
  'field_tax_calc'       => 'Исчисленный налог',
  'field_tax_due'        => 'Налог к уплате',
  'field_tax_paid'       => 'Уплачено',
  'field_total_due'      => 'К доплате',
  'field_ipn'            => 'ИПН',
  'field_opv'            => 'ОПВ',
  'field_sn'             => 'СН',
  'field_so'             => 'СО',
  'field_osms'           => 'ОСМС',
  'field_vosms'          => 'ВОСМС',
  'field_emp_count'      => 'Численность работников',
  'field_land_area'      => 'Площадь земли',
  'field_land_tax'       => 'Налог на землю',
  'field_property_value' => 'Стоимость имущества',
  'field_property_tax'   => 'Налог на имущество',
  'field_transport_tax'  => 'Налог на транспорт',
  'field_vat_taxable'    => 'Облагаемый оборот',
  'field_vat_amount'     => 'НДС',
  'field_note'           => 'Примечание',

  // --- Представители ---
  'rep_title'            => 'Представители',
  'rep_add'              => 'Добавить представителя',
  'rep_iin'              => 'ИИН представителя',
  'rep_name'             => 'ФИО представителя',
  'rep_role'             => 'Роль',
  'rep_access'           => 'Доступ',
  'rep_added'            => 'Представитель добавлен',
  'rep_removed'          => 'Представитель удалён',
  'rep_no_reps'          => 'Нет представителей',

  // --- ЭЦП ---
  'ecp_title'            => 'Электронная цифровая подпись',
  'ecp_your_cert'        => 'Ваш сертификат',
  'ecp_serial'           => 'Серийный номер',
  'ecp_valid_to'         => 'Действителен до',
  'ecp_download'         => 'Скачать .p12',
  'ecp_regenerate'       => 'Перегенерировать',
  'ecp_active'           => 'Активен',
  'ecp_expired'          => 'Истёк',
  'ecp_info'             => 'Сертификат ЭЦП используется для подписания деклараций',

  // --- Подача ---
  'submit_title'         => 'Подача декларации',
  'submit_choose_form'   => 'Выберите форму декларации',
  'submit_recent'        => 'Недавно поданные',
  'submit_popular'       => 'Популярные формы',
  'submit_all_forms'     => 'Все формы',

  // --- Футер ---
  'footer_address'       => '010000, г. Астана, пр. Мәңгілік Ел, 8',
  'footer_phone'         => '8 (7172) 70-99-47',
  'footer_hotline'       => '1414 — бесплатно',

  // --- Сообщения об ошибках форм ---
  'err_iin_required'     => 'Введите ИИН',
  'err_iin_format'       => 'ИИН должен содержать 12 цифр',
  'err_iin_exists'       => 'Пользователь с таким ИИН уже зарегистрирован',
  'err_lastname'         => 'Введите фамилию',
  'err_firstname'        => 'Введите имя',
  'err_birthdate'        => 'Введите дату рождения',
  'err_password_short'   => 'Пароль не менее 6 символов',
  'err_password_match'   => 'Пароли не совпадают',
  'err_login'            => 'Неверный ИИН или пароль',
  'err_required'         => 'Поле обязательно для заполнения',
],

// ============================================================
// КАЗАХСКИЙ
// ============================================================
'kz' => [

  // --- Общие ---
  'site_name'            => 'Салық төлеуші кабинеті',
  'site_sub'             => 'Қазақстан Республикасы',
  'loading'              => 'Жүктелуде...',
  'save'                 => 'Сақтау',
  'cancel'               => 'Болдырмау',
  'close'                => 'Жабу',
  'delete'               => 'Жою',
  'edit'                 => 'Өңдеу',
  'back'                 => 'Артқа',
  'back_to_list'         => 'Тізімге оралу',
  'continue'             => 'Жалғастыру',
  'submit'               => 'Тапсыру',
  'confirm'              => 'Растау',
  'yes'                  => 'Иә',
  'no'                   => 'Жоқ',
  'search'               => 'Іздеу',
  'filter'               => 'Сүзгі',
  'all'                  => 'Барлығы',
  'none'                 => 'Жоқ',
  'required_field'       => 'Міндетті өріс',
  'optional_field'       => 'Міндетті емес',
  'error'                => 'Қате',
  'success'              => 'Сәтті',
  'warning'              => 'Ескерту',
  'info'                 => 'Ақпарат',
  'not_found'            => 'Табылмады',
  'access_denied'        => 'Рұқсат жоқ',
  'unknown_error'        => 'Белгісіз қате',
  'copied'               => 'Көшірілді',
  'show_all'             => 'Барлығын көрсету',
  'go_to_doc'            => 'Құжатқа өту',
  'open'                 => 'Ашу',
  'download'             => 'Жүктеп алу',
  'print'                => 'Басып шығару',
  'view'                 => 'Қарау',
  'sign'                 => 'Қол қою',
  'send'                 => 'Жіберу',
  'year'                 => 'Жыл',
  'period'               => 'Кезең',
  'date'                 => 'Күні',
  'sum'                  => 'Сомасы',
  'action'               => 'Әрекет',
  'type'                 => 'Түрі',
  'status'               => 'Мәртебесі',
  'name'                 => 'Атауы',
  'inn'                  => 'ЖСН',
  'bin'                  => 'БСН',
  'inn_bin'              => 'ЖСН/БСН',
  'phone'                => 'Телефон',
  'email'                => 'Email',
  'address'              => 'Мекенжай',
  'created_at'           => 'Жасалған күні',
  'updated_at'           => 'Жаңартылған күні',
  'language'             => 'Тіл',
  'settings'             => 'Параметрлер',
  'help'                 => 'Көмек',
  'logout'               => 'Шығу',
  'my_profile'           => 'Менің профилім',
  'hotline'              => 'Жедел желі',
  'telegram_bot'         => 'Telegram-бот',
  'copyright'            => '© {year} ҚР Қаржы министрлігі',
  'privacy'              => 'Құпиялылық саясаты',
  'terms'                => 'Пайдалану шарттары',

  // --- Навигация ---
  'nav_services'         => 'Қызметтер',
  'nav_account'          => 'Жеке шот',
  'nav_services_menu'    => 'Сервистер',
  'nav_documents'        => 'Құжаттар',
  'nav_submit_doc'       => 'Декларация тапсыру',
  'nav_representatives'  => 'Өкілдер',
  'nav_profile'          => 'Профиль',
  'nav_overview'         => 'Шолу',
  'nav_history'          => 'Төлем тарихы',
  'nav_debts'            => 'Берешектер',
  'nav_overpayment'      => 'Артық төлем',
  'nav_charges'          => 'Есептеулер',
  'nav_calculator'       => 'Салық калькуляторы',
  'nav_notifications'    => 'Хабарламалар',
  'nav_messages'         => 'Хабарлар',
  'nav_all_documents'    => 'Барлық құжаттар',
  'nav_incoming'         => 'Кіріс',
  'nav_new_document'     => 'Жаңа құжат',
  'nav_feedback'         => 'Кері байланыс',
  'nav_submit_btn'       => 'Декларация тапсыру',
  'nav_support'          => 'Қолдау',
  'nav_help'             => 'Анықтама орталығы',

  // --- Статусы ---
  'status_draft'         => 'Жоба',
  'status_submitted'     => 'Қарастырылуда',
  'status_in_review'     => 'Тексерілуде',
  'status_accepted'      => 'Қабылданды',
  'status_rejected'      => 'Қабылданбады',
  'status_cancelled'     => 'Күші жойылды',
  'status_paid'          => 'Төленді',
  'status_unpaid'        => 'Төленбеді',
  'status_overdue'       => 'Мерзімі өтті',
  'status_new'           => 'Жаңа',
  'status_read'          => 'Оқылды',

  // --- Дашборд ---
  'dashboard_title'      => 'Жеке кабинет',
  'dashboard_welcome'    => 'Қош келдіңіз',
  'my_documents'         => 'Менің құжаттарым',
  'incoming_documents'   => 'Кіріс құжаттар',
  'messages'             => 'Хабарлар',
  'submit_documents'     => 'Құжаттарды тапсыру',
  'representatives_card' => 'Өкілдер',
  'no_documents'         => 'Құжаттар жоқ',
  'no_incoming'          => 'Кіріс құжаттар жоқ',
  'no_messages'          => 'Хабарлар жоқ',
  'no_representatives'   => 'Өкілдер қосылмаған',
  'no_notifications'     => 'Хабарламалар жоқ',
  'tab_my_docs'          => 'Менің құжаттарым',
  'tab_incoming'         => 'Кіріс',
  'doc_form'             => 'Нысан',
  'doc_date'             => 'Күні',
  'doc_status'           => 'Мәртебесі',
  'doc_actions'          => 'Әрекеттер',
  'user_type_individual' => 'Жеке тұлға',
  'user_type_ip'         => 'Жеке кәсіпкер',
  'user_type_legal'      => 'Заңды тұлға',

  // --- Лицевой счёт ---
  'account_title'        => 'Жеке шот',
  'account_overview'     => 'Шолу',
  'account_documents'    => 'Құжаттар',
  'account_history'      => 'Төлем тарихы',
  'account_debts'        => 'Берешектер',
  'account_overpayment'  => 'Артық төлем',
  'account_charges'      => 'Есептеулер',
  'account_profile'      => 'Профиль',
  'total_documents'      => 'Барлық құжаттар',
  'total_debt'           => 'Берешек сомасы',
  'total_overpayment'    => 'Артық төлем сомасы',
  'paid_current_year'    => 'Осы жылы төленді',
  'recent_documents'     => 'Соңғы құжаттар',
  'recent_activity'      => 'Соңғы әрекеттер',
  'payment_history'      => 'Төлем тарихы',
  'debts_label'          => 'Берешектер',
  'overpayment_label'    => 'Артық төлем',
  'charges_label'        => 'Есептеулер',
  'no_debts'             => 'Берешек жоқ',
  'no_overpayment'       => 'Артық төлем жоқ',
  'no_charges'           => 'Есептеулер жоқ',
  'no_history'           => 'Төлем тарихы бос',
  'debt_progress'        => 'Өтеу прогресі',
  'paid_amount'          => 'Төленді',
  'remaining_amount'     => 'Қалдық',
  'charge_type'          => 'Есептеу түрі',
  'charge_period'        => 'Кезең',
  'charge_amount'        => 'Есептеу сомасы',
  'charge_paid'          => 'Төленді',
  'charge_balance'       => 'Баланс',
  'filter_all'           => 'Барлығы',
  'filter_year'          => 'Жыл',
  'doc_filter_status'    => 'Мәртебе',
  'delete_draft'         => 'Жобаны жою',

  // --- Документы ---
  'documents_title'      => 'Құжаттар',
  'doc_number'           => '№ құжат',
  'doc_type'             => 'Декларация түрі',
  'doc_period'           => 'Салықтық кезең',
  'doc_submitted_at'     => 'Тапсырылған күні',
  'doc_created_at'       => 'Жасалған күні',
  'doc_view'             => 'Қарау',
  'doc_continue'         => 'Жалғастыру',
  'doc_delete'           => 'Жою',
  'doc_download_pdf'     => 'PDF жүктеу',
  'doc_view_pdf'         => 'PDF қарау',
  'doc_sign'             => 'ЭЦҚ-мен қол қою',
  'doc_submit'           => 'Декларация тапсыру',
  'no_docs_found'        => 'Құжаттар табылмады',
  'search_docs'          => 'Құжаттарды іздеу',
  'advanced_filter'      => 'Сүзгілер',

  // --- Просмотр документа ---
  'doc_view_title'       => 'Құжатты қарау',
  'doc_info'             => 'Құжат туралы ақпарат',
  'taxpayer'             => 'Салық төлеуші',
  'doc_timeline'         => 'Өңдеу тарихы',
  'timeline_created'     => 'Жасалды',
  'timeline_submitted'   => 'Тапсырылды',
  'timeline_review'      => 'Тексерілуде',
  'timeline_final'       => 'Қорытынды мәртебе',
  'timeline_pending'     => 'Күтуде',
  'doc_comment'          => 'Пікір',
  'doc_reject_reason'    => 'Қабылдамау себебі',
  'doc_form_data'        => 'Декларация деректері',
  'doc_no_data'          => 'Деректер толтырылмаған',
  'support_info'         => 'Көмек керек пе?',
  'support_text'         => 'Telegram немесе жедел желі арқылы бізге хабарласыңыз.',
  'status_sub_draft'     => 'Жоба тапсырылмаған',
  'status_sub_submitted' => 'Қарастырылуды күтуде',
  'status_sub_inreview'  => 'Тексеруде',
  'status_sub_accepted'  => 'Декларация қабылданды',
  'status_sub_rejected'  => 'Декларация қабылданбады',
  'status_sub_cancelled' => 'Құжат күші жойылды',

  // --- Уведомления ---
  'notifications_title'  => 'Хабарламалар',
  'notif_all'            => 'Барлық хабарламалар',
  'notif_unread'         => 'Оқылмаған',
  'notif_read'           => 'Оқылған',
  'notif_mark_all'       => 'Барлығын оқылды деп белгілеу',
  'notif_del_read'       => 'Оқылғандарды жою',
  'notif_types_title'    => 'Түрі бойынша',
  'notif_clear_filter'   => 'Сүзгіні тазалау',
  'notif_empty_all'      => 'Хабарламалар жоқ',
  'notif_empty_unread'   => 'Барлық хабарламалар оқылды',
  'notif_empty_sub'      => 'Мұнда құжаттарыңыз бен салықтарыңыз туралы хабарламалар көрсетіледі',
  'notif_empty_sub_read' => 'Оқылған хабарламалар жоқ',
  'notif_mark_read'      => 'Оқылды деп белгілеу',
  'notif_count'          => 'хабарлама',
  'notif_unread_count'   => 'оқылмаған',
  'confirm_del_read'     => 'Барлық оқылған хабарламаларды жою керек пе?',
  'notif_toast_marked'   => 'Барлық хабарламалар оқылды',
  'notif_toast_deleted'  => 'Оқылған хабарламалар жойылды',
  'notif_type_document'  => 'Құжаттар',
  'notif_type_deadline'  => 'Мерзімдер',
  'notif_type_system'    => 'Жүйе',
  'notif_type_payment'   => 'Төлемдер',
  'notif_min_ago'        => '{n} мин. бұрын',
  'notif_hour_ago'       => '{n} сағ. бұрын',
  'notif_day_ago'        => '{n} күн бұрын',
  'notif_week_ago'       => '{n} апта бұрын',
  'notif_just_now'       => 'Жаңа ғана',
  'notif_read_at'        => 'Оқылды',
  'notif_pagination'     => '{page} / {total} бет',

  // --- Профиль ---
  'profile_title'        => 'Профиль',
  'profile_personal'     => 'Жеке деректер',
  'profile_contacts'     => 'Байланыс ақпараты',
  'profile_security'     => 'Қауіпсіздік',
  'profile_settings'     => 'Параметрлер',
  'profile_ecp'          => 'ЭЦҚ',
  'profile_fullname'     => 'Т.А.Ж.',
  'profile_lastname'     => 'Тегі',
  'profile_firstname'    => 'Аты',
  'profile_midname'      => 'Әкесінің аты',
  'profile_birthdate'    => 'Туған күні',
  'profile_user_type'    => 'Салық төлеуші түрі',
  'profile_reg_date'     => 'Тіркелген күні',
  'profile_last_login'   => 'Соңғы кіру',
  'change_password'      => 'Құпиясөзді өзгерту',
  'current_password'     => 'Ағымдағы құпиясөз',
  'new_password'         => 'Жаңа құпиясөз',
  'confirm_password'     => 'Құпиясөзді растаңыз',
  'password_changed'     => 'Құпиясөз сәтті өзгертілді',
  'password_error'       => 'Ағымдағы құпиясөз қате',
  'passwords_not_match'  => 'Құпиясөздер сәйкес емес',
  'password_too_short'   => 'Құпиясөз кем дегенде 6 таңбадан тұруы керек',
  'profile_saved'        => 'Деректер сақталды',

  // --- Вход / Регистрация ---
  'login_title'          => 'Кабинетке кіру',
  'login_iin'            => 'ЖСН',
  'login_password'       => 'Құпиясөз',
  'login_submit'         => 'Кіру',
  'login_ecp'            => 'ЭЦҚ арқылы кіру',
  'login_no_account'     => 'Аккаунт жоқ па?',
  'login_register'       => 'Тіркелу',
  'login_forgot'         => 'Құпиясөзді ұмыттыңыз ба?',
  'login_error'          => 'ЖСН немесе құпиясөз қате',
  'login_blocked'        => 'Аккаунт бұғатталған',
  'register_title'       => 'Тіркелу',
  'register_step1'       => 'Жеке деректер',
  'register_step2'       => 'Қауіпсіздік',
  'register_step3'       => 'ЭЦҚ',
  'register_iin'         => 'ЖСН (12 сан)',
  'register_lastname'    => 'Тегі',
  'register_firstname'   => 'Аты',
  'register_midname'     => 'Әкесінің аты',
  'register_birthdate'   => 'Туған күні',
  'register_phone'       => 'Телефон',
  'register_email'       => 'Email',
  'register_password'    => 'Құпиясөз (кемінде 6 таңба)',
  'register_password2'   => 'Құпиясөзді қайталаңыз',
  'register_submit'      => 'Тіркелу',
  'register_have_account'=> 'Аккаунт бар ма?',
  'register_login'       => 'Кіру',
  'register_iin_invalid' => 'ЖСН 12 санды болуы керек',
  'register_iin_exists'  => 'Бұл ЖСН-мен пайдаланушы тіркелген',
  'register_ecp_info'    => 'Тіркелгеннен кейін ЭЦҚ сертификаты (.p12) автоматты түрде жасалады',
  'register_success_title'=> 'Тіркелу аяқталды!',
  'register_personal_data'=> 'Жеке деректер',
  'register_password_data'=> 'Құпиясөз және қауіпсіздік',
  'password_strength_1'  => 'Әлсіз',
  'password_strength_2'  => 'Орташа',
  'password_strength_3'  => 'Жақсы',
  'password_strength_4'  => 'Күшті',
  'passwords_match'      => 'Құпиясөздер сәйкес келеді',

  // --- Калькулятор ---
  'calculator_title'     => 'Салық калькуляторы',
  'calc_tax_type'        => 'Салық түрі',
  'calc_income'          => 'Кіріс',
  'calc_deduction'       => 'Шегерімдер',
  'calc_result'          => 'Есептеу нәтижесі',
  'calc_tax_amount'      => 'Салық сомасы',
  'calc_calculate'       => 'Есептеу',
  'calc_reset'           => 'Тазалау',
  'calc_opv'             => 'МЗА (зейнетақы)',
  'calc_co'              => 'ӘС (әлеуметтік аударымдар)',
  'calc_osms'            => 'МӘМС',
  'calc_ipn'             => 'ЖТС (жеке табыс салығы)',
  'calc_sn'              => 'ӘС (әлеуметтік салық)',

  // --- Формы ---
  'form_title'           => '{code} нысаны',
  'form_taxpayer_info'   => 'Салық төлеуші туралы мәліметтер',
  'form_tax_period'      => 'Салықтық кезең',
  'form_correction'      => 'Түзету',
  'form_correction_num'  => 'Түзету нөмірі',
  'form_is_correction'   => 'Түзетуші болып табылады',
  'form_sign_date'       => 'Қол қою күні',
  'form_next'            => 'Келесі',
  'form_prev'            => 'Артқа',
  'form_save_draft'      => 'Жобаны сақтау',
  'form_submit'          => 'Қол қою және тапсыру',
  'form_ecp_required'    => 'Қол қою үшін ЭЦҚ қажет',
  'form_saved'           => 'Жоба сақталды',
  'form_submitted'       => 'Декларация сәтті тапсырылды',

  // --- Поля ---
  'field_iin'            => 'ЖСН',
  'field_bin'            => 'БСН',
  'field_fullname'       => 'Т.А.Ж. / Атауы',
  'field_phone'          => 'Телефон',
  'field_email'          => 'Email',
  'field_address'        => 'Мекенжай',
  'field_tax_office'     => 'Салық органы',
  'field_year'           => 'Жыл',
  'field_period'         => 'Кезең',
  'field_revenue'        => 'Жиынтық табыс',
  'field_income'         => 'Табыс',
  'field_total_income'   => 'Табыстар барлығы',
  'field_total_deduct'   => 'Шегерімдер барлығы',
  'field_tax_base'       => 'Салық базасы',
  'field_tax_rate'       => 'Салық мөлшерлемесі',
  'field_tax_calc'       => 'Есептелген салық',
  'field_tax_due'        => 'Төленетін салық',
  'field_tax_paid'       => 'Төленді',
  'field_total_due'      => 'Қосымша төлемге',
  'field_ipn'            => 'ЖТС',
  'field_opv'            => 'МЗА',
  'field_sn'             => 'ӘС',
  'field_so'             => 'ӘА',
  'field_osms'           => 'МӘМС',
  'field_vosms'          => 'МӘМС жарнасы',
  'field_emp_count'      => 'Қызметкерлер саны',
  'field_land_area'      => 'Жер алаңы',
  'field_land_tax'       => 'Жер салығы',
  'field_property_value' => 'Мүліктің құны',
  'field_property_tax'   => 'Мүлік салығы',
  'field_transport_tax'  => 'Көлік салығы',
  'field_vat_taxable'    => 'Салық салынатын айналым',
  'field_vat_amount'     => 'ҚҚС',
  'field_note'           => 'Ескерту',

  // --- Представители ---
  'rep_title'            => 'Өкілдер',
  'rep_add'              => 'Өкіл қосу',
  'rep_iin'              => 'Өкілдің ЖСН-і',
  'rep_name'             => 'Өкілдің Т.А.Ж.',
  'rep_role'             => 'Рөл',
  'rep_access'           => 'Рұқсат',
  'rep_added'            => 'Өкіл қосылды',
  'rep_removed'          => 'Өкіл жойылды',
  'rep_no_reps'          => 'Өкілдер жоқ',

  // --- ЭЦП ---
  'ecp_title'            => 'Электрондық цифрлық қолтаңба',
  'ecp_your_cert'        => 'Сіздің сертификатыңыз',
  'ecp_serial'           => 'Сериялық нөмір',
  'ecp_valid_to'         => 'Жарамдылық мерзімі',
  'ecp_download'         => '.p12 жүктеу',
  'ecp_regenerate'       => 'Қайта жасау',
  'ecp_active'           => 'Белсенді',
  'ecp_expired'          => 'Мерзімі өтті',
  'ecp_info'             => 'ЭЦҚ сертификаты декларацияларға қол қою үшін пайдаланылады',

  // --- Подача ---
  'submit_title'         => 'Декларация тапсыру',
  'submit_choose_form'   => 'Декларация нысанын таңдаңыз',
  'submit_recent'        => 'Жуырда тапсырылған',
  'submit_popular'       => 'Танымал нысандар',
  'submit_all_forms'     => 'Барлық нысандар',

  // --- Футер ---
  'footer_address'       => '010000, Астана қ., Мәңгілік Ел д-лы, 8',
  'footer_phone'         => '8 (7172) 70-99-47',
  'footer_hotline'       => '1414 — тегін',

  // --- Ошибки ---
  'err_iin_required'     => 'ЖСН енгізіңіз',
  'err_iin_format'       => 'ЖСН 12 саннан тұруы керек',
  'err_iin_exists'       => 'Бұл ЖСН-мен пайдаланушы тіркелген',
  'err_lastname'         => 'Тегіңізді енгізіңіз',
  'err_firstname'        => 'Атыңызды енгізіңіз',
  'err_birthdate'        => 'Туған күнді енгізіңіз',
  'err_password_short'   => 'Құпиясөз кемінде 6 таңба',
  'err_password_match'   => 'Құпиясөздер сәйкес емес',
  'err_login'            => 'ЖСН немесе құпиясөз қате',
  'err_required'         => 'Өріс міндетті түрде толтырылуы керек',
],

// ============================================================
// АНГЛИЙСКИЙ
// ============================================================
'en' => [

  // --- Общие ---
  'site_name'            => 'Taxpayer Cabinet',
  'site_sub'             => 'Republic of Kazakhstan',
  'loading'              => 'Loading...',
  'save'                 => 'Save',
  'cancel'               => 'Cancel',
  'close'                => 'Close',
  'delete'               => 'Delete',
  'edit'                 => 'Edit',
  'back'                 => 'Back',
  'back_to_list'         => 'Back to list',
  'continue'             => 'Continue',
  'submit'               => 'Submit',
  'confirm'              => 'Confirm',
  'yes'                  => 'Yes',
  'no'                   => 'No',
  'search'               => 'Search',
  'filter'               => 'Filter',
  'all'                  => 'All',
  'none'                 => 'None',
  'required_field'       => 'Required field',
  'optional_field'       => 'Optional',
  'error'                => 'Error',
  'success'              => 'Success',
  'warning'              => 'Warning',
  'info'                 => 'Info',
  'not_found'            => 'Not found',
  'access_denied'        => 'Access denied',
  'unknown_error'        => 'Unknown error',
  'copied'               => 'Copied',
  'show_all'             => 'Show all',
  'go_to_doc'            => 'Go to document',
  'open'                 => 'Open',
  'download'             => 'Download',
  'print'                => 'Print',
  'view'                 => 'View',
  'sign'                 => 'Sign',
  'send'                 => 'Send',
  'year'                 => 'Year',
  'period'               => 'Period',
  'date'                 => 'Date',
  'sum'                  => 'Amount',
  'action'               => 'Action',
  'type'                 => 'Type',
  'status'               => 'Status',
  'name'                 => 'Name',
  'inn'                  => 'IIN',
  'bin'                  => 'BIN',
  'inn_bin'              => 'IIN/BIN',
  'phone'                => 'Phone',
  'email'                => 'Email',
  'address'              => 'Address',
  'created_at'           => 'Created date',
  'updated_at'           => 'Updated date',
  'language'             => 'Language',
  'settings'             => 'Settings',
  'help'                 => 'Help',
  'logout'               => 'Log out',
  'my_profile'           => 'My profile',
  'hotline'              => 'Hotline',
  'telegram_bot'         => 'Telegram bot',
  'copyright'            => '© {year} Ministry of Finance RK',
  'privacy'              => 'Privacy Policy',
  'terms'                => 'Terms of Use',

  // --- Навигация ---
  'nav_services'         => 'Services',
  'nav_account'          => 'My Account',
  'nav_services_menu'    => 'Tools',
  'nav_documents'        => 'Documents',
  'nav_submit_doc'       => 'File a Return',
  'nav_representatives'  => 'Representatives',
  'nav_profile'          => 'Profile',
  'nav_overview'         => 'Overview',
  'nav_history'          => 'Payment History',
  'nav_debts'            => 'Debts',
  'nav_overpayment'      => 'Overpayment',
  'nav_charges'          => 'Charges',
  'nav_calculator'       => 'Tax Calculator',
  'nav_notifications'    => 'Notifications',
  'nav_messages'         => 'Messages',
  'nav_all_documents'    => 'All Documents',
  'nav_incoming'         => 'Incoming',
  'nav_new_document'     => 'New Document',
  'nav_feedback'         => 'Feedback',
  'nav_submit_btn'       => 'File a Return',
  'nav_support'          => 'Support',
  'nav_help'             => 'Help Center',

  // --- Статусы ---
  'status_draft'         => 'Draft',
  'status_submitted'     => 'Under Review',
  'status_in_review'     => 'Being Reviewed',
  'status_accepted'      => 'Accepted',
  'status_rejected'      => 'Rejected',
  'status_cancelled'     => 'Cancelled',
  'status_paid'          => 'Paid',
  'status_unpaid'        => 'Unpaid',
  'status_overdue'       => 'Overdue',
  'status_new'           => 'New',
  'status_read'          => 'Read',

  // --- Дашборд ---
  'dashboard_title'      => 'Personal Cabinet',
  'dashboard_welcome'    => 'Welcome',
  'my_documents'         => 'My Documents',
  'incoming_documents'   => 'Incoming Documents',
  'messages'             => 'Messages',
  'submit_documents'     => 'Submit Documents',
  'representatives_card' => 'Representatives',
  'no_documents'         => 'No documents yet',
  'no_incoming'          => 'No incoming documents',
  'no_messages'          => 'No messages yet',
  'no_representatives'   => 'No representatives added',
  'no_notifications'     => 'No notifications',
  'tab_my_docs'          => 'My Documents',
  'tab_incoming'         => 'Incoming',
  'doc_form'             => 'Form',
  'doc_date'             => 'Date',
  'doc_status'           => 'Status',
  'doc_actions'          => 'Actions',
  'user_type_individual' => 'Individual',
  'user_type_ip'         => 'Sole Proprietor',
  'user_type_legal'      => 'Legal Entity',

  // --- Лицевой счёт ---
  'account_title'        => 'My Account',
  'account_overview'     => 'Overview',
  'account_documents'    => 'Documents',
  'account_history'      => 'Payment History',
  'account_debts'        => 'Debts',
  'account_overpayment'  => 'Overpayment',
  'account_charges'      => 'Charges',
  'account_profile'      => 'Profile',
  'total_documents'      => 'Total Documents',
  'total_debt'           => 'Total Debt',
  'total_overpayment'    => 'Total Overpayment',
  'paid_current_year'    => 'Paid This Year',
  'recent_documents'     => 'Recent Documents',
  'recent_activity'      => 'Recent Activity',
  'payment_history'      => 'Payment History',
  'debts_label'          => 'Debts',
  'overpayment_label'    => 'Overpayment',
  'charges_label'        => 'Charges',
  'no_debts'             => 'No debts',
  'no_overpayment'       => 'No overpayment',
  'no_charges'           => 'No charges',
  'no_history'           => 'Payment history is empty',
  'debt_progress'        => 'Repayment Progress',
  'paid_amount'          => 'Paid',
  'remaining_amount'     => 'Remaining',
  'charge_type'          => 'Charge Type',
  'charge_period'        => 'Period',
  'charge_amount'        => 'Charge Amount',
  'charge_paid'          => 'Paid',
  'charge_balance'       => 'Balance',
  'filter_all'           => 'All',
  'filter_year'          => 'Year',
  'doc_filter_status'    => 'Status',
  'delete_draft'         => 'Delete Draft',

  // --- Документы ---
  'documents_title'      => 'Documents',
  'doc_number'           => 'Doc #',
  'doc_type'             => 'Declaration Type',
  'doc_period'           => 'Tax Period',
  'doc_submitted_at'     => 'Submitted Date',
  'doc_created_at'       => 'Created Date',
  'doc_view'             => 'View',
  'doc_continue'         => 'Continue',
  'doc_delete'           => 'Delete',
  'doc_download_pdf'     => 'Download PDF',
  'doc_view_pdf'         => 'View PDF',
  'doc_sign'             => 'Sign with EDS',
  'doc_submit'           => 'File Declaration',
  'no_docs_found'        => 'No documents found',
  'search_docs'          => 'Search documents',
  'advanced_filter'      => 'Filters',

  // --- Просмотр документа ---
  'doc_view_title'       => 'Document View',
  'doc_info'             => 'Document Information',
  'taxpayer'             => 'Taxpayer',
  'doc_timeline'         => 'Processing History',
  'timeline_created'     => 'Created',
  'timeline_submitted'   => 'Submitted for Review',
  'timeline_review'      => 'Under Review',
  'timeline_final'       => 'Final Status',
  'timeline_pending'     => 'Pending',
  'doc_comment'          => 'Comment',
  'doc_reject_reason'    => 'Rejection Reason',
  'doc_form_data'        => 'Declaration Data',
  'doc_no_data'          => 'Data not filled',
  'support_info'         => 'Need help?',
  'support_text'         => 'Contact us via Telegram or hotline.',
  'status_sub_draft'     => 'Draft not submitted',
  'status_sub_submitted' => 'Awaiting review',
  'status_sub_inreview'  => 'Being reviewed',
  'status_sub_accepted'  => 'Declaration accepted',
  'status_sub_rejected'  => 'Declaration rejected',
  'status_sub_cancelled' => 'Document cancelled',

  // --- Уведомления ---
  'notifications_title'  => 'Notifications',
  'notif_all'            => 'All Notifications',
  'notif_unread'         => 'Unread',
  'notif_read'           => 'Read',
  'notif_mark_all'       => 'Mark all as read',
  'notif_del_read'       => 'Delete read',
  'notif_types_title'    => 'By Type',
  'notif_clear_filter'   => 'Clear filter',
  'notif_empty_all'      => 'No notifications',
  'notif_empty_unread'   => 'All notifications are read',
  'notif_empty_sub'      => 'Notifications about your documents and taxes will appear here',
  'notif_empty_sub_read' => 'No read notifications',
  'notif_mark_read'      => 'Mark as read',
  'notif_count'          => 'notifications',
  'notif_unread_count'   => 'unread',
  'confirm_del_read'     => 'Delete all read notifications?',
  'notif_toast_marked'   => 'All notifications marked as read',
  'notif_toast_deleted'  => 'Read notifications deleted',
  'notif_type_document'  => 'Documents',
  'notif_type_deadline'  => 'Deadlines',
  'notif_type_system'    => 'System',
  'notif_type_payment'   => 'Payments',
  'notif_min_ago'        => '{n} min ago',
  'notif_hour_ago'       => '{n} h ago',
  'notif_day_ago'        => '{n} d ago',
  'notif_week_ago'       => '{n} wk ago',
  'notif_just_now'       => 'Just now',
  'notif_read_at'        => 'Read',
  'notif_pagination'     => 'Page {page} of {total}',

  // --- Профиль ---
  'profile_title'        => 'Profile',
  'profile_personal'     => 'Personal Data',
  'profile_contacts'     => 'Contact Information',
  'profile_security'     => 'Security',
  'profile_settings'     => 'Settings',
  'profile_ecp'          => 'Digital Signature',
  'profile_fullname'     => 'Full Name',
  'profile_lastname'     => 'Last Name',
  'profile_firstname'    => 'First Name',
  'profile_midname'      => 'Middle Name',
  'profile_birthdate'    => 'Date of Birth',
  'profile_user_type'    => 'Taxpayer Type',
  'profile_reg_date'     => 'Registration Date',
  'profile_last_login'   => 'Last Login',
  'change_password'      => 'Change Password',
  'current_password'     => 'Current Password',
  'new_password'         => 'New Password',
  'confirm_password'     => 'Confirm Password',
  'password_changed'     => 'Password changed successfully',
  'password_error'       => 'Incorrect current password',
  'passwords_not_match'  => 'Passwords do not match',
  'password_too_short'   => 'Password must be at least 6 characters',
  'profile_saved'        => 'Data saved',

  // --- Вход / Регистрация ---
  'login_title'          => 'Sign In',
  'login_iin'            => 'IIN',
  'login_password'       => 'Password',
  'login_submit'         => 'Sign In',
  'login_ecp'            => 'Sign in with EDS',
  'login_no_account'     => 'No account?',
  'login_register'       => 'Register',
  'login_forgot'         => 'Forgot password?',
  'login_error'          => 'Invalid IIN or password',
  'login_blocked'        => 'Account is blocked',
  'register_title'       => 'Registration',
  'register_step1'       => 'Personal Data',
  'register_step2'       => 'Security',
  'register_step3'       => 'EDS',
  'register_iin'         => 'IIN (12 digits)',
  'register_lastname'    => 'Last Name',
  'register_firstname'   => 'First Name',
  'register_midname'     => 'Middle Name',
  'register_birthdate'   => 'Date of Birth',
  'register_phone'       => 'Phone',
  'register_email'       => 'Email',
  'register_password'    => 'Password (min. 6 characters)',
  'register_password2'   => 'Repeat Password',
  'register_submit'      => 'Register',
  'register_have_account'=> 'Already have an account?',
  'register_login'       => 'Sign In',
  'register_iin_invalid' => 'IIN must contain 12 digits',
  'register_iin_exists'  => 'A user with this IIN already exists',
  'register_ecp_info'    => 'After registration, an EDS certificate (.p12) will be generated automatically',
  'register_success_title'=> 'Registration complete!',
  'register_personal_data'=> 'Personal Data',
  'register_password_data'=> 'Password & Security',
  'password_strength_1'  => 'Weak',
  'password_strength_2'  => 'Fair',
  'password_strength_3'  => 'Good',
  'password_strength_4'  => 'Strong',
  'passwords_match'      => 'Passwords match',

  // --- Калькулятор ---
  'calculator_title'     => 'Tax Calculator',
  'calc_tax_type'        => 'Tax Type',
  'calc_income'          => 'Income',
  'calc_deduction'       => 'Deductions',
  'calc_result'          => 'Calculation Result',
  'calc_tax_amount'      => 'Tax Amount',
  'calc_calculate'       => 'Calculate',
  'calc_reset'           => 'Reset',
  'calc_opv'             => 'OPV (Pension)',
  'calc_co'              => 'CO (Social Contributions)',
  'calc_osms'            => 'OSMS',
  'calc_ipn'             => 'IPN (Personal Income Tax)',
  'calc_sn'              => 'SN (Social Tax)',

  // --- Формы ---
  'form_title'           => 'Form {code}',
  'form_taxpayer_info'   => 'Taxpayer Information',
  'form_tax_period'      => 'Tax Period',
  'form_correction'      => 'Correction',
  'form_correction_num'  => 'Correction Number',
  'form_is_correction'   => 'Is a corrective filing',
  'form_sign_date'       => 'Signing Date',
  'form_next'            => 'Next',
  'form_prev'            => 'Back',
  'form_save_draft'      => 'Save Draft',
  'form_submit'          => 'Sign & Submit',
  'form_ecp_required'    => 'EDS required to sign',
  'form_saved'           => 'Draft saved',
  'form_submitted'       => 'Declaration submitted successfully',

  // --- Поля ---
  'field_iin'            => 'IIN',
  'field_bin'            => 'BIN',
  'field_fullname'       => 'Full Name / Entity Name',
  'field_phone'          => 'Phone',
  'field_email'          => 'Email',
  'field_address'        => 'Address',
  'field_tax_office'     => 'Tax Authority',
  'field_year'           => 'Year',
  'field_period'         => 'Period',
  'field_revenue'        => 'Total Revenue',
  'field_income'         => 'Income',
  'field_total_income'   => 'Total Income',
  'field_total_deduct'   => 'Total Deductions',
  'field_tax_base'       => 'Tax Base',
  'field_tax_rate'       => 'Tax Rate',
  'field_tax_calc'       => 'Calculated Tax',
  'field_tax_due'        => 'Tax Due',
  'field_tax_paid'       => 'Paid',
  'field_total_due'      => 'Additional Payment',
  'field_ipn'            => 'IPN',
  'field_opv'            => 'OPV',
  'field_sn'             => 'SN',
  'field_so'             => 'SO',
  'field_osms'           => 'OSMS',
  'field_vosms'          => 'VOSMS',
  'field_emp_count'      => 'Employee Count',
  'field_land_area'      => 'Land Area',
  'field_land_tax'       => 'Land Tax',
  'field_property_value' => 'Property Value',
  'field_property_tax'   => 'Property Tax',
  'field_transport_tax'  => 'Transport Tax',
  'field_vat_taxable'    => 'Taxable Turnover',
  'field_vat_amount'     => 'VAT',
  'field_note'           => 'Note',

  // --- Представители ---
  'rep_title'            => 'Representatives',
  'rep_add'              => 'Add Representative',
  'rep_iin'              => 'Representative IIN',
  'rep_name'             => 'Representative Name',
  'rep_role'             => 'Role',
  'rep_access'           => 'Access',
  'rep_added'            => 'Representative added',
  'rep_removed'          => 'Representative removed',
  'rep_no_reps'          => 'No representatives',

  // --- ЭЦП ---
  'ecp_title'            => 'Electronic Digital Signature',
  'ecp_your_cert'        => 'Your Certificate',
  'ecp_serial'           => 'Serial Number',
  'ecp_valid_to'         => 'Valid Until',
  'ecp_download'         => 'Download .p12',
  'ecp_regenerate'       => 'Regenerate',
  'ecp_active'           => 'Active',
  'ecp_expired'          => 'Expired',
  'ecp_info'             => 'EDS certificate is used to sign tax declarations',

  // --- Подача ---
  'submit_title'         => 'File a Declaration',
  'submit_choose_form'   => 'Choose a declaration form',
  'submit_recent'        => 'Recently Filed',
  'submit_popular'       => 'Popular Forms',
  'submit_all_forms'     => 'All Forms',

  // --- Футер ---
  'footer_address'       => '010000, Astana, Mangilik El Ave., 8',
  'footer_phone'         => '8 (7172) 70-99-47',
  'footer_hotline'       => '1414 — free',

  // --- Ошибки ---
  'err_iin_required'     => 'Please enter IIN',
  'err_iin_format'       => 'IIN must contain 12 digits',
  'err_iin_exists'       => 'A user with this IIN already exists',
  'err_lastname'         => 'Please enter last name',
  'err_firstname'        => 'Please enter first name',
  'err_birthdate'        => 'Please enter date of birth',
  'err_password_short'   => 'Password must be at least 6 characters',
  'err_password_match'   => 'Passwords do not match',
  'err_login'            => 'Invalid IIN or password',
  'err_required'         => 'This field is required',
],

]; // end $LANG
